### ISSUE TITLE
avoid volume rendering objects to slow down the GUI when changing palette

### ISSUE THREAD

**Issue by denisri** [brainvisa/anatomist-free#1]
---

Author Name: **Riviere, Denis** (@denisri)
Original Redmine Issue: 1646, https://bioproj.extra.cea.fr/redmine/issues/1646
Original Date: 2010-08-21
Original Assignee: Riviere, Denis

---

from http://brainvisa.info/forum/viewtopic.php?f=6&t=1487:

add the possibility to freeze rendering in a window. Since volume rendrering can be quite slow. It would be very useful to stop volume rendering update while playing with palettes (in some windows we may want to see the palette update) and reactivate it later. One can do that by closing the window containing VR object but all the scene is lost (window size, objects in the window, point of view, clipping, etc.).
Yann

How would you think the user interface for such a "freeze" would be like ?
The best would probably be to update volume rendering objects in a separate thread with a possibility of interruption, so that the GUI is not frozen, and new changes in palettes would stop the unfinished update (and start a new update). It should also be possible to perform a "coarse-to-fine" update to display quickly an undersampled volume rendering. All this would maybe need a bit of infrastructure work, since the changed/update flags in objects are not designed to be asynchronous and I am not completely sure it would work well in the curent state, even it it would probably not require a lot of work.
Denis

**Comment by denisri** [comment]
---

Original Redmine Comment
Author Name: **Cointepas, Yann** (@sapetnioc)
Original Date: 2012-06-14T12:25:48Z

---

My first idea would be to try to make things being automatic. Views can be classified on their update speed according to the type of objects in it. If we identify two kinds of view : slow update and fast update, it may be possible to keep the actual update behavior for fast views and to make slow views only record that they have to be modified on existing events. Actual modification of slow views could be done separately ; for instance at idle time or by a timer event fired every few seconds.

Another possibility could be to define a fast view for each object. For fast rendering object the fast view could be the standard view. But for slow rendering object it can be completely different (for example a simple bounding box for volume rendering). User could switch between fast/slow views in different ways : globaly for all view of Anatomist (with a button, menu and/or keyboard shortcut), per view or per object. I have the feeling that the global option is simpler to understand and to use. The user just choose to put Anatomist in fast rendering mode, play with palettes etc. and switch back to normal mode when done. Fast rendering can be interesting also for the selection of point of view on complex scenes (i.e. you cannot just freeze the display here).

**Comment by sapetnioc** [comment]
What about closing this old issue ?
If not, could we use window minimization to stop rendering updates ? Minimizing a window would stop any update but keep scene attributes. A full refresh would be done when window is restored.

**Comment by denisri** [comment]
Window minimization would flicker and disturb the window manager, would it not ?

**Comment by sapetnioc** [comment]
I am not sure we are talking of the same thing. Maybe minimization is not the right term. I was thinking of this button next to the window close button allowing to reduce (and hide) a window. Such reduced windows could stop refreshing their content and use as few resource as possible.

**Comment by denisri** [comment]
Yes I think that's it: but either it is a user action, or the program will hide the window, then show it again later, which would be very disturbing for the user. Moreover when a rendering has started, it still goes all the way and blocks until this refresh is finished (even if the window is hidden). In non-GPU renderings it can be enough to be annoying.
Well, anyway volume rendering is not used everyday and fixing it is too much work for now, so OK to close.
