### ISSUE TITLE
Fusion2D working in image intensity space

### ISSUE THREAD

**Issue by denisri** [brainvisa/anatomist-free#2]
---

Author Name: **Riviere, Denis** (@denisri)
Original Redmine Issue: 7772, https://bioproj.extra.cea.fr/redmine/issues/7772
Original Date: 2013-06-24
Original Assignee: Riviere, Denis

---

Currently, 2D fusions operate in RGB space, after application of the colormap of each volume.
It would be useful to have fusions in the initial intensity (or label) space, to allow better and easier operations (masking, difference, addition etc). Ibn this case, colormap should be applied after fusionning.
It may be implemented either in the current Fusion2D object, or in a new fusion object type. The latter would perhaps be more convenient and easier to implement because it has its own colormap and fusion mixing types, contrarily to the Fusion2D object, which relies on individual volumes colormaps.
Such a fusion should afterwards be usable in a Fusion2D.

**Comment by sapetnioc** [comment]
Is this still an enhancement project or cant the issue be closed ?

**Comment by denisri** [comment]
It could be an interesting enhancement, but not a real need, and it would require a significant amount of work (so it has never been implemented). I'm OK to close it until we find time for it ( ;) )
