### ISSUE TITLE
“Save resampled” keeps the 'referential' attribute even when it changes the referential

### ISSUE THREAD

**Issue by ylep** [brainvisa/anatomist-free#24]
It seems that “Save resampled” adjusts the field of view of the resampled image, but it still keeps the `referential` attribute of the reference image, so we end up with two images with the same referential uuid, which represent different referentials.

**Comment by denisri** [comment]
There was a problem in header settings of the resampled volume, which should be fixed now.
Does the problem still happen ?
Normally the resampled volume should get the same referential as the target image (and not keep its initial one).

**Comment by denisri** [comment]
I close this issue - if it's not fixed please reopen it.
