### ISSUE TITLE
Fusion3D does not work correctly with RGB volumes

### ISSUE THREAD

**Issue by denisri** [brainvisa/anatomist-free#3]
---

Author Name: **Riviere, Denis** (@denisri)
Original Redmine Issue: 8113, https://bioproj.extra.cea.fr/redmine/issues/8113
Original Date: 2013-09-10
Original Assignee: Riviere, Denis

---

The resulting texture is either all black, or black / white.

**Comment by denisri** [comment]
---

Original Redmine Comment
Author Name: **Riviere, Denis** (@denisri)
Original Date: 2013-10-17T23:21:15Z

---

requires some "real" work, not just a fix, because it implies RGB textures, not palette + tex coords. Or it may be done using the 4 R,G,B,A palettes as in texture interpolation, but it's not just 5 minutes work.

**Comment by sapetnioc** [comment]
Should we keep this issue opened ?

**Comment by denisri** [comment]
No, it's not a priority.
